# GHA for test-linux-stable-int, test-linux-stable, test-linux-stable-oldkernel
name: test-linux-stable-runtime-benchmarks

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # isdraft:
  #   uses: ./.github/workflows/reusable-isdraft.yml
  preflight:
    # needs: isdraft
    uses: ./.github/workflows/reusable-preflight.yml

  # https://github.com/paritytech/ci_cd/issues/864
  test-linux-stable-runtime-benchmarks:
    needs: [preflight]
    strategy:
      matrix:
        run: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      fail-fast: false
    if: ${{ needs.preflight.outputs.changes_rust }}
    runs-on: ${{ needs.preflight.outputs.RUNNER }}
    timeout-minutes: 60
    container:
      image: ${{ needs.preflight.outputs.IMAGE }}
    env:
      RUST_TOOLCHAIN: stable
      # Enable debug assertions since we are running optimized builds for testing
      # but still want to have debug assertions.
      RUSTFLAGS: "-Cdebug-assertions=y -Dwarnings"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: script
        id: required
        run: forklift cargo nextest run --workspace --features runtime-benchmarks benchmark --locked --cargo-profile testnet
      # - name: Stop all workflows if failed
      #   if: ${{ failure() && steps.required.conclusion == 'failure' && !github.event.pull_request.head.repo.fork }}
      #   uses: ./.github/actions/workflow-stopper
      #   with:
      #     app-id: ${{ secrets.WORKFLOW_STOPPER_RUNNER_APP_ID }}
      #     app-key: ${{ secrets.WORKFLOW_STOPPER_RUNNER_APP_KEY }}
