# GHA for test-linux-stable-int, test-linux-stable, test-linux-stable-oldkernel
name: test-linux-stable-runtime-benchmarks

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # isdraft:
  #   uses: ./.github/workflows/reusable-isdraft.yml
  preflight:
    # needs: isdraft
    uses: ./.github/workflows/reusable-preflight.yml

  # https://github.com/paritytech/ci_cd/issues/864

  # test-linux-stable-runtime-benchmarks-1:
  #   needs: [preflight]
  #   # if: ${{ needs.preflight.outputs.changes_rust }}
  #   runs-on: parity-test
  #   timeout-minutes: 120
  #   container:
  #     image: ${{ needs.preflight.outputs.IMAGE }}
  #   env:
  #     RUST_TOOLCHAIN: stable
  #     # Enable debug assertions since we are running optimized builds for testing
  #     # but still want to have debug assertions.
  #     RUSTFLAGS: "-Cdebug-assertions=y -Dwarnings"
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         ref: "771c9988e2a636a150d97c10e3122af8068d1687"
  #     - name: script
  #       id: required
  #       run: |
  #         /builds/download-forklift.sh -v master && forklift version
  #         forklift cargo nextest run --workspace --features runtime-benchmarks benchmark --locked --cargo-profile testnet

  test-linux-stable-runtime-benchmarks:
    needs: [preflight]
    strategy:
      matrix:
        run: [1, 2, 3, 4, 5]
      fail-fast: false
    # if: ${{ needs.preflight.outputs.changes_rust }}
    runs-on: parity-large
    timeout-minutes: 120
    container:
      image: ${{ needs.preflight.outputs.IMAGE }}
    env:
      RUST_TOOLCHAIN: stable
      # Enable debug assertions since we are running optimized builds for testing
      # but still want to have debug assertions.
      RUSTFLAGS: "-Cdebug-assertions=y -Dwarnings"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: fl
        run: /builds/download-forklift.sh -v 0.14.1 && forklift version && forklift config show    
      - name: script
        id: required
        run: |
          forklift cargo nextest run --workspace --features runtime-benchmarks benchmark --locked --cargo-profile testnet

      - run: ls -al target/forklift
      # - name: Stop all workflows if failed
      #   if: ${{ failure() && steps.required.conclusion == 'failure' && !github.event.pull_request.head.repo.fork }}
      #   uses: ./.github/actions/workflow-stopper
      #   with:
      #     app-id: ${{ secrets.WORKFLOW_STOPPER_RUNNER_APP_ID }}
      #     app-key: ${{ secrets.WORKFLOW_STOPPER_RUNNER_APP_KEY }}

  test-linux-stable:
    needs: [preflight]
    if: ${{ needs.preflight.outputs.changes_rust }}
    runs-on: ${{ matrix.runners }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        partition: [1/3, 2/3, 3/3]
        runners:
          [
            "${{ needs.preflight.outputs.RUNNER }}",
            "${{ needs.preflight.outputs.RUNNER_OLDLINUX }}",
          ]
    container:
      image: ${{ needs.preflight.outputs.IMAGE }}
      # needed for tests that use unshare syscall
      options: --security-opt seccomp=unconfined
    env:
      RUST_TOOLCHAIN: stable
      # Enable debug assertions since we are running optimized builds for testing
      # but still want to have debug assertions.
      RUSTFLAGS: "-Cdebug-assertions=y -Dwarnings"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: fl
        run: /builds/download-forklift.sh -v master && forklift version && forklift config show
      - name: script
        id: required
        run: |
          # Fixes "detected dubious ownership" error in the ci
          git config --global --add safe.directory '*'
          forklift cargo nextest run \
            --workspace \
            --locked \
            --release \
            --no-fail-fast \
            --cargo-quiet \
            --features try-runtime,experimental,ci-only-tests \
            --partition count:${{ matrix.partition }}
      # run runtime-api tests with `enable-staging-api` feature on the 1st node
      - name: runtime-api tests
        if: ${{ matrix.partition == '1/3' }}
        run: forklift cargo nextest run -p sp-api-test --features enable-staging-api --cargo-quiet
